### ISSUE TITLE
AttributeError: No attribute AttentionPosition

### ISSUE THREAD

**Issue by Samitkk18** [nicknochnack/RealTimeObjectDetection#13]
Traceback (most recent call last):
  File "Tensorflow/models/research/object_detection/model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "/Users/samitkapadia/opt/anaconda3/envs/sign/lib/python3.7/site-packages/object_detection/model_lib_v2.py", line 30, in <module>
    from object_detection import inputs
  File "/Users/samitkapadia/opt/anaconda3/envs/sign/lib/python3.7/site-packages/object_detection/inputs.py", line 26, in <module>
    from object_detection.builders import model_builder
  File "/Users/samitkapadia/opt/anaconda3/envs/sign/lib/python3.7/site-packages/object_detection/builders/model_builder.py", line 36, in <module>
    from object_detection.meta_architectures import context_rcnn_meta_arch
  File "/Users/samitkapadia/opt/anaconda3/envs/sign/lib/python3.7/site-packages/object_detection/meta_architectures/context_rcnn_meta_arch.py", line 42, in <module>
    class ContextRCNNMetaArch(faster_rcnn_meta_arch.FasterRCNNMetaArch):
  File "/Users/samitkapadia/opt/anaconda3/envs/sign/lib/python3.7/site-packages/object_detection/meta_architectures/context_rcnn_meta_arch.py", line 95, in ContextRCNNMetaArch
    faster_rcnn_pb2.AttentionPosition.POST_BOX_CLASSIFIER)
AttributeError: module 'object_detection.protos.faster_rcnn_pb2' has no attribute 'AttentionPosition'

**Comment by Samitkk18** [comment]
After cloning the tensorflow/models repository go to the following link and follow the steps
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md
