### ISSUE TITLE
Generate_tfrecord.py parse error

### ISSUE THREAD

**Issue by arifbintanga** [nicknochnack/RealTimeObjectDetection#15]
I change nothing from your original file, and I ran the cell for "generating tf records". It showed error messages like this
Traceback (most recent call last):
  File "Tensorflow/scripts/generate_tfrecord.py", line 170, in <module>
    tf.app.run()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "Tensorflow/scripts/generate_tfrecord.py", line 157, in main
    examples = xml_to_csv(args.xml_dir)
  File "Tensorflow/scripts/generate_tfrecord.py", line 81, in xml_to_csv
    tree = ET.parse(xml_file)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

Can you help me. It created the null file inside annotation folders

**Comment by StarvedHawk** [comment]
im having the same issue but only when doing the test tf record, I even had it running around 2 months ago so idk what changed

**Comment by arifbintanga** [comment]
I actually managed to solve the problem, but I forget to write it up when I did. Could you check the spesific line of generate_tf record syntax and make sure that it was not "commented". I'm pretty sure my problem occurred because of my careless checking through every line of code, after impatiently hitting the run button for writing a bit here and there in the code. So it would be possible that you run to the same problem because of careless checking too.

ps. you can paste the scripts here and let me check which part that might cause the issue.

**Comment by StarvedHawk** [comment]
This was the Cell i was running : 
 `!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/train'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}`

`!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x{IMAGE_PATH + '/test'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}`

The Output: 

> Successfully created the TFRecord file: Tensorflow/workspace/annotations/train.record

>Traceback (most recent call last):
  File "Tensorflow/scripts/generate_tfrecord.py", line 166, in <module>
    tf.app.run()
  File "C:\Users\faisa\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\faisa\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\faisa\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "Tensorflow/scripts/generate_tfrecord.py", line 153, in main
    examples = xml_to_csv(args.xml_dir)
  File "Tensorflow/scripts/generate_tfrecord.py", line 79, in xml_to_csv
    tree = ET.parse(xml_file)
  File "C:\Users\faisa\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Users\faisa\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 3


The Generate tf records works for train but fails for test

**Comment by StarvedHawk** [comment]
I realized that the error is coming because of a faulty XML file so I will be editing the code to handle the error and give me the file name.

Changes made in the **generate_tfrecord.py** file, Function **xml_to_csv(path)**:

```
def xml_to_csv(path):
    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        try:
           tree = ET.parse(xml_file)
           root = tree.getroot()
           for member in root.findall('object'):
               value = (root.find('filename').text,
                     int(root.find('size')[0].text),
                     int(root.find('size')[1].text),
                     member[0].text,
                     int(member[4][0].text),
                     int(member[4][1].text),
                     int(member[4][2].text),
                     int(member[4][3].text)
                     )
               xml_list.append(value)
        except xml.etree.ElementTree.ParseError as error:
           print("\n\t---There is an error in file ",xml_file,"\n")
    column_name = ['filename', 'width', 'height',
                   'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df
```
In case an xml label is faulty this will output an error message in the terminal detailing which label is faulty
