### ISSUE TITLE
error when creating TF records

### ISSUE THREAD

**Issue by abdulrhman-adel** [nicknochnack/RealTimeObjectDetection#23]
I have an error when running 
```
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/train'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x{IMAGE_PATH + '/test'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}
```
error:

```
Traceback (most recent call last):
  File "F:\Robo\Sign detector\Tensorflow\scripts\generate_tfrecord.py", line 168, in <module>
    tf.app.run()
  File "C:\Users\abdul\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\abdul\.conda\envs\tensorflow\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\abdul\.conda\envs\tensorflow\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "F:\Robo\Sign detector\Tensorflow\scripts\generate_tfrecord.py", line 158, in main
    tf_example = create_tf_example(group, path)
  File "F:\Robo\Sign detector\Tensorflow\scripts\generate_tfrecord.py", line 132, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "F:\Robo\Sign detector\Tensorflow\scripts\generate_tfrecord.py", line 101, in class_text_to_int
    return label_map_dict[row_label]
KeyError: 'yes'
```

I hope anyone can help me.
Thanks in advance

**Comment by A-l-Mahi** [comment]
Have you fixed it?

**Comment by A-l-Mahi** [comment]
Hello I have found a solution! Check this.
https://stackoverflow.com/questions/70559949/tensorflow-python-lib-io-pywrap-file-io-bufferedinputstreamfilename-str-buff

**Comment by abdulrhman-adel** [comment]
it worked! thanks

**Comment by sravaniy123** [comment]
But after changing no tf record is created. Can Someone please help.

**Comment by srav-and** [comment]
But after changing no tf record is created. Can Someone please help.
