### ISSUE TITLE
gfile

### ISSUE THREAD

**Issue by ab5fr** [nicknochnack/RealTimeObjectDetection#42]
i have tried to change tf.gfile.gfile to tf.io.gfile and same error

```
2023-09-09 21:56:44.780502: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-09-09 21:56:44.780726: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:\Users\ASUS\Desktop\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
AttributeError: module 'tensorflow' has no attribute 'gfile'
```

**Comment by apotato369550** [comment]
I'm stuck on the same error. Any progress?

**Comment by kurda-kurda** [comment]
pip install tensorflow-object-detection-api
