### ISSUE TITLE
error creating in creating tf record

### ISSUE THREAD

**Issue by parasyadav08** [nicknochnack/RealTimeObjectDetection#44]
Traceback (most recent call last):
  File "C:\Users\Pictures\sign recognition\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "C:\Users\Pictures\sign recognition\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\PARAS YADAV\AppData\Roaming\Python\Python311\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\object_detection\protos\string_int_label_map_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 please tell how to resolve this error

**Comment by apotato369550** [comment]
Add this line to the notebook:
`!pip install protobuf==3.20.*`
