### ISSUE TITLE
Getting error when trying to create TF records

### ISSUE THREAD

**Issue by Rockntt** [nicknochnack/RealTimeObjectDetection#48]
Hi, @nicknochnack . Trying to follow your object detection guide, but getting this error: 

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python.lib.io._pywrap_file_io.TransactionToken = None)
    
Got no thoughts how to fix it. Looking for help!

**Comment by AbuNim61** [comment]
hello @nicknochnack  i have troubel when i run tf record 
the eror looks like this 
Traceback (most recent call last):
  File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 62, in <module>
    label_map_dict = label_map_util.get_label_map_dict(label_map)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 166, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 135, in load_labelmap
    label_map_string =  tf.io.gfile.GFile(path, 'r').read()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\tensorflow\python\lib\io\file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python.lib.io._pywrap_file_io.BufferedInputStream(filename: str, buffer_size: int, token: tensorflow.python.lib.io._pywrap_file_io.TransactionToken = None)

Invoked with: item {
  name: "aku"
  id: 1
}
item {
  name: "cinta"
  id: 2
...
  name: "makan"
  id: 5
}
, 524288

i have change the dataset. whats wrong ?

**Comment by AbuNim61** [comment]
i got the error like this 
Traceback (most recent call last):
  File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
         ^^^^^^^^
AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?
Traceback (most recent call last):
  File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in <module>
    label_map = label_map_util.load_labelmap(args.labels_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\RealTimeObjectDetection\.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
         ^^^^^^^^
AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?

**Comment by Rockntt** [comment]
> i got the error like this Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'? Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?

Hi,

The repository seems to be dead and the notebook is outdated. Try to look for a newer guides.

**Comment by AbuNim61** [comment]
> > i got the error like this Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'? Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?
> 
> Hi,
> 
> The repository seems to be dead and the notebook is outdated. Try to look for a newer guides.

i've solve that eror but now i found other one 

Traceback (most recent call last):
  File "[E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29](file:///E:/RealTimeObjectDetection/Tensorflow/scripts/generate_tfrecord.py#line=28), in <module>
    from object_detection.utils import dataset_util, label_map_util
ModuleNotFoundError: No module named 'object_detection'
Traceback (most recent call last):
  File "[E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29](file:///E:/RealTimeObjectDetection/Tensorflow/scripts/generate_tfrecord.py#line=28), in <module>
    from object_detection.utils import dataset_util, label_map_util
ModuleNotFoundError: No module named 'object_detection'

how to fix it?

**Comment by Rockntt** [comment]
> > > i got the error like this Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'? Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?
> > 
> > 
> > Hi,
> > The repository seems to be dead and the notebook is outdated. Try to look for a newer guides.
> 
> i've solve that eror but now i found other one
> 
> Traceback (most recent call last): File "E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util ModuleNotFoundError: No module named 'object_detection' Traceback (most recent call last): File "E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29, in from object_detection.utils import dataset_util, label_map_util ModuleNotFoundError: No module named 'object_detection'
> 
> how to fix it?

Try install Tensorflow Object Detection Library Packaged
```
pip install tensorflow-object-detection-api
```

**Comment by vishwas-sanyal** [comment]
> > > i got the error like this Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'? Traceback (most recent call last): File "e:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 61, in label_map = label_map_util.load_labelmap(args.labels_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "e:\RealTimeObjectDetection.venv\Lib\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap with tf.gfile.GFile(path, 'r') as fid: ^^^^^^^^ AttributeError: module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?
> > 
> > Hi,
> > 
> > The repository seems to be dead and the notebook is outdated. Try to look for a newer guides.
> 
> i've solve that eror but now i found other one 
> 
> Traceback (most recent call last):
>   File "[E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29](file:///E:/RealTimeObjectDetection/Tensorflow/scripts/generate_tfrecord.py#line=28), in <module>
>     from object_detection.utils import dataset_util, label_map_util
> ModuleNotFoundError: No module named 'object_detection'
> Traceback (most recent call last):
>   File "[E:\RealTimeObjectDetection\Tensorflow\scripts\generate_tfrecord.py", line 29](file:///E:/RealTimeObjectDetection/Tensorflow/scripts/generate_tfrecord.py#line=28), in <module>
>     from object_detection.utils import dataset_util, label_map_util
> ModuleNotFoundError: No module named 'object_detection'
> 
> how to fix it?

hello @AbuNim61 
can you explan how you fix the "module 'tensorflow' has no attribute 'gfile'. Did you mean: 'fill'?" error
